config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'session#show'

  # Site-wide functionality.
  scope '/_' do
    authpwn_session
    resources :courses, only: [:index, :new, :create] do
      collection do
        get :connect
      end
    end

    # Account registration.
    resources :users do
      collection do
        post :check_email
      end
      member do
        post :impersonate
        patch :set_admin
        patch :confirm_email
      end
    end
    resources :profile_photos do
      member do
        get :profile, :thumb
      end
    end

    # Staff registration.
    resources :roles, only: [:destroy]

    # Background jobs.
    resources :jobs, only: [:index, :show] do
      collection do
        delete :failed, action: :destroy_failed
      end
    end

    # API.
    scope '/api', defaults: { format: 'json' } do
      get '0/user_info' => 'api#user_info', as: :api_user_info_v0
      get '0/assignments' => 'api#assignments', as: :api_assignments_v0
      get '0/submissions' => 'api#submissions', as: :api_submissions_v0
    end

    # API documentation.
    get 'api_docs' => 'api_docs#index', as: :api_docs

    # E-mail resolver configuration.
    resources :email_resolvers

    # E-mail SMTP server configuration.
    resource :smtp_server, only: [:edit, :update]

    resources :feedback, only: [:new]

    # Exception handling test.
    get '/crash' => 'crash#crash'
  end

  # Course-specific URLs. Most functionality falls here.
  scope '/:id', constraints: { id: /[^\/]+/ } do
    get 'course(.:format)', to: 'courses#show', as: :course
    patch 'course(.:format)', to: 'courses#update'
    delete 'course(.:format)', to: 'courses#destroy'
    get 'course/edit(.:format)', to: 'courses#edit', as: :edit_course
  end

  scope '/:course_id', constraints: { course_id: /[^\/]+/ } do
    # TODO(pwnall): remove the format specifier when the following bug gets
    #               fixed - https://github.com/rails/rails/issues/22747
    root 'session#show', as: :course_root, format: 'html'

    resources :prerequisites, except: [:show]
    resources :time_slots, only: [:index, :create, :destroy]

    # Student registration.
    resources :registrations,
              only: [:index, :show, :new, :create, :edit, :update] do
      member do
        patch :restricted
      end
    end

    # Staff registration.
    resources :role_requests, only: [:index, :new, :create, :show, :destroy] do
      member do
        post :approve
        post :deny
      end
    end

    # Recitations.
    resources :recitation_sections, except: [:show] do
      collection do
        post :autoassign
      end
    end
    resources :recitation_partitions, only: [:index, :show, :destroy]  do
      member do
        post :implement
      end
    end

    # Homework.
    resources :assignments do
      member do
        get :dashboard
        patch :schedule
        patch :deschedule
        patch :release
        patch :unrelease
        patch :release_grades
      end
      resources :extensions, controller: :deadline_extensions,
          only: [:index, :create]
    end
    resources :deadline_extensions, only: [:destroy]
    resources :assignment_files, only: [] do
      member do
        get :download
      end
    end
    resources :grades, only: [:index, :create] do
      collection do
        get :editor
        get :request_report, :request_missing
        post :for_user, :missing, :report
      end
    end
    resources :grade_comments, only: [:create]
    resources :exams, only: [] do
      resources :attendances, controller: :exam_attendances, only: [:index]
    end
    resources :exam_sessions, only: [] do
      resources :attendances, controller: :exam_attendances, only: [:create]
    end
    resources :attendances, controller: :exam_attendances, only: [:update,
        :destroy]

    # Homework submission.
    resources :analyzers, only: [] do
      collection do
        get :help
      end
      member do
        get :source
      end
    end
    resources :deliverables do
      member do
        get :submission_dashboard
        post :reanalyze
      end
    end
    resources :assignment_metrics
    resources :submissions, only: [:index, :create, :destroy] do
      member do
        get :file
        post :reanalyze
        post :promote
      end
      collection do
        get :request_package
        post :xhr_deliverables
        post :package_assignment
      end
      resources :collaborations, only: [:create, :destroy], shallow: true
    end
    resources :analyses, only: [:show] do
      member do
        get :refresh
      end
    end

    # Surveys.
    scope shallow_prefix: :survey do
      resources :surveys do
        resources :responses, controller: :survey_responses,
            only: [:index, :create, :update], shallow: true
      end
    end

    # Teams.
    resources :team_memberships, only: [:create, :destroy]
    resources :team_partitions do
      member do
        patch :lock
        patch :unlock
        get :issues
      end
    end

    resources :teams, only: [:edit, :create, :update, :destroy]
    # Teams / Student view.
    get '/teams_student', to: 'teams_student#show'
    post '/teams_student/leave_team', to: 'teams_student#leave_team', as: :leave_team
    post '/teams_student/create_team', to: 'teams_student#create_team'
    post '/teams_student/invite_member', to: 'teams_student#invite_member'
    post '/teams_student/accept_invitation', to: 'teams_student#accept_invitation'
    post '/teams_student/ignore_invitation', to: 'teams_student#ignore_invitation'
    resources :teams_student
  end

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/session.rb
# Virtual model for the information collected when a user signs in.
class Session
  include Authpwn::SessionModel

  # Add your extensions to the Session class here.
end

app/controllers/session_controller.rb
# Manages logging in and out of the application.
class SessionController < ApplicationController
  include Authpwn::SessionController

  # Sets up the 'session/welcome' view. No user is logged in.
  def welcome
    set_current_course if params[:course_id]

    @session = Session.from_params params
    respond_to do |format|
      format.html { render action: :new }
      format.json { render json: {} }
    end
  end
  private :welcome

  # Sets up the 'session/home' view. A user is logged in.
  def home
    set_current_course if params[:course_id]

    respond_to do |format|
      format.html do
        if current_course.nil? && !current_user.admin?
          course_count = current_user.registered_courses.count +
              current_user.employed_courses.count
          if course_count == 0
            redirect_to connect_courses_url
            return
          end
          if course_count == 1
            redirect_to course_root_url(course_id:
                current_user.registered_courses.first ||
                current_user.employed_courses.first)
            return
          end
        end

        # Pull information about the current user.
        @news_flavor = params[:flavor] ? params[:flavor].to_sym : nil
      end
      format.json { }
    end
  end
  private :home

  # The notification text displayed when a session authentication fails.
  def bounce_notice_text(reason)
    case reason
    when :invalid
      'Invalid e-mail or password'
    when :expired
      'Password expired. Please click "Forget password"'
    when :blocked
      'Account blocked. Please verify your e-mail address'
    end
  end

  # A user is logged in, based on a token.
  def home_with_token(token)
    respond_to do |format|
      format.html do
        case token
        when Tokens::EmailVerification
          redirect_to session_url, notice: 'E-mail address confirmed'
        when Tokens::PasswordReset
          redirect_to change_password_session_url
        # Handle other token types here.
        end
      end
      format.json do
        # Rely on default behavior.
      end
    end
  end
  private :home_with_token

  # If true, every successful login results in a SQL query that removes expired
  # session tokens from the database, to keep its size down.
  #
  # For better performance, set this to false and periodically call
  # Tokens::SessionUid.remove_expired in background thread.
  self.auto_purge_sessions = true

  # You shouldn't extend the session controller, so you can benefit from future
  # features. But, if you must, you can do it here.
end

app/controllers/sessions_controller.rb
class SessionController < ApplicationController
  protect_from_forgery :except => [:create, :destroy, :logout]
    
  # POST /session
  def create
    session[:user_id] = nil
    @login = User.new params[:user]    
    user = User.authenticate @login.email, @login.password
    if user.nil?
      flash[:error] = 'Invalid user/password combination'
    elsif !user.active
      bounce_user("Your account is inactive (did you confirm your #{@login.email} e-mail address?)")
      return
    else
      session[:user_id] = user.id
      @current_user = user
    end
    
    respond_to do |format|
      if session[:user_id]
        format.html { redirect_to root_path }
      else
        format.html do
          @login.reset_password
          render :action => :welcome
        end
      end
    end    
  end
  
  # DELETE /session
  def destroy
    session[:user_id] = nil
    response.headers['X-Account-Management-Status'] = "none"
    flash[:notice] = 'You have been logged out'
    respond_to do |format|
      format.html { redirect_to root_path }
    end    
  end
  
  # GET /session/logout
  # POST /session/logout
  def logout
    destroy
  end
  
  # GET /session
  def index
    if current_user
      @news_flavor = params[:flavor] ? params[:flavor].to_sym : nil
      render :action => :home
    else
      render :action => :welcome
    end
  end
end

app/views/session/_deadlines.html.erb
<div id="deadlines-sidebar">
  <h3>Deadlines</h3>

  <ol class="deadline-list no-bullet">
  <% ActionItem.for(current_user, current_course).each do |item| %>
    <li class="deadline-<%= item.state %>">
      <div class="deadline-indicator">
        <%= deadline_state_icon_tag item.state %>
      </div>
      <div class="task">
        <div class="main-task task-link">
          <%= link_to item.subject.name,
                polymorphic_path(item.subject, course_id: item.subject.course) %>
          <%= "(#{item.subject.course.number})" unless current_course %>
        </div>
        <% if item.subject.instance_of? Assignment %>
          <div class="sub-task task-link">
            <%= link_to item.description, self.send(*item.link) %>
          </div>
        <% end %>
      </div>
      <div class="date" title="<%= item.due_at.to_s(:deadline_long) %>">
        <%= item.due_at.to_s(:deadline_short) %>
      </div>
    </li>
  <% end %>
  </ol>
</div>

app/views/session/_login_form.html.erb
<% if @redirect_url %>
<p>
  We need you to log in before we can show you the page that you are trying to
  view.
</p>
<% end %>

<%= foundation_form_for @session, url: session_path do |f| %>
  <%= f.email_field :email, label: 'Email Address' %>
  <%= f.password_field :password, label: 'Password' %>

  <div class="row align-center">
    <div class="small-5 columns">
      <%= f.button 'Log in', name: 'login', value: 'requested',
            class: 'hollow expanded button' %>
    </div>
    <div class="small-5 columns">
      <%= f.button 'Reset Password', name: 'reset_password', value: 'requested',
            formaction: reset_password_session_path,
            class: 'hollow expanded button' %>
    </div>
  </div>

  <% if @redirect_url %>
  <%= hidden_field_tag :redirect_url, @redirect_url %>
  <% end %>
<% end %>

app/views/session/_sidebar.html.erb
<% if current_user %>
  <%= render 'session/deadlines' %>
  <%= render 'layouts/groups' %>
<% else %>
  <h2>Welcome</h2>

  <% if current_course %>
  <p>
    This is the homework submission website for MIT course
    <%= current_course.number %>, <%= current_course.title %>.
  </p>
  <%= render 'session/deadlines' %>
  <% end %>
<% end %>

app/views/session/api_token.html.erb
<h2>API Token</h2>

<p class="lead">
  Use the API token below to allow third-party applications to interact with
  your Igor account. This is your personal token, so keep it discrete and use it
  only with applications that you trust. If you accidentally expose your token,
  generate a new token to replace it.
</p>

<div id="api-token-actions">
  <div class="input-group">
    <%= text_field_tag 'api_token', current_user.api_token, readonly: true,
          class: 'input-group-field' %>
    <%= button_tag type: 'button', class: 'input-group-button',
                   data: { clipboard_target: '#api_token' } do %>
      <%= clipboard_copy_icon_tag %>
    <% end %>
  </div>

  <span class="link-button-wrapper">
    <%= link_to destroy_api_token_session_path, method: :delete do %>
      <%= refresh_icon_tag %> Regenerate token
    <% end %>
  </span>
</div>

<p>
  The site's public API is documented <%= link_to 'here', api_docs_path %>.
</p>

app/views/session/forbidden.html.erb
<% if current_user %>
<p>
  You are not allowed to perform this action.  
  Please  <%= link_to 'sign off', session_path, :method => :delete %>, and 
  sign in as a different user.  
</p>
<% else %>
<p>
  Unfortunately, you have disabled JavaScript in your browser. Please go to the
  <%= link_to 'home page', new_session_path %> manually.
</p>
<script type="text/javascript">
window.location = "<%= new_session_path %>";
</script>
<% end %>

app/views/session/home.html.erb
<%= render 'layouts/newsfeed' %>

app/views/session/new.html.erb
<section class="login">
  <h2>Sign in</h2>
  <%= render 'session/login_form' %>
</section>

<section class="register-hint">
  <h2>No account?</h2>
  <%= form_tag new_user_path, method: :get do %>
    <div class="row align-center">
      <div class="small-6 columns">
        <button class="hollow expanded button">Register</button>
      </div>
    </div>
  <% end %>
</section>

app/views/session/password_change.html.erb
<h2>Password Reset</h2>

<% if @credential.updated_at %>
<p class="lead password_age_notice">
  Your have been using the same password for
  <span class="password_age">
    <%= time_ago_in_words @credential.updated_at, include_seconds: true %>.
  </span>
</p>
<% end %>

<%= foundation_form_for @credential, url: change_password_session_path,
                          as: :credential, method: :post do |f| %>

  <% unless @credential.new_record? %>
    <%= f.password_field :old_password, label: 'Current Password' %>
  <% end %>

  <%= f.password_field :password, required: true, placeholder: 'be clever',
        data: { pwnfx_confirm: 'new-password' }, label: 'New Password' %>

  <%= f.row do %>
    <%= f.password_field :password_confirmation, required: true,
          placeholder: 'can you type that again?',
          data: { pwnfx_confirm: 'new-password' }, label: 'Re-enter Password' %>
    <div class="columns">
      <span class="error-text middle" data-pwnfx-confirm-win="new-password">
        <%= valid_icon_tag %> matches
      </span>
      <span class="error-text middle" data-pwnfx-confirm-fail="new-password">
        <%= invalid_icon_tag %> does not match
      </span>
    </div>
  <% end %>

  <%= submit_button_tag do %>
    <%= save_icon_tag %> Save New Password
  <% end %>
<% end %>