config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'session#show'

  # Site-wide functionality.
  scope '/_' do
    authpwn_session
    resources :courses, only: [:index, :new, :create] do
      collection do
        get :connect
      end
    end

    # Account registration.
    resources :users do
      collection do
        post :check_email
      end
      member do
        post :impersonate
        patch :set_admin
        patch :confirm_email
      end
    end
    resources :profile_photos do
      member do
        get :profile, :thumb
      end
    end

    # Staff registration.
    resources :roles, only: [:destroy]

    # Background jobs.
    resources :jobs, only: [:index, :show] do
      collection do
        delete :failed, action: :destroy_failed
      end
    end

    # API.
    scope '/api', defaults: { format: 'json' } do
      get '0/user_info' => 'api#user_info', as: :api_user_info_v0
      get '0/assignments' => 'api#assignments', as: :api_assignments_v0
      get '0/submissions' => 'api#submissions', as: :api_submissions_v0
    end

    # API documentation.
    get 'api_docs' => 'api_docs#index', as: :api_docs

    # E-mail resolver configuration.
    resources :email_resolvers

    # E-mail SMTP server configuration.
    resource :smtp_server, only: [:edit, :update]

    resources :feedback, only: [:new]

    # Exception handling test.
    get '/crash' => 'crash#crash'
  end

  # Course-specific URLs. Most functionality falls here.
  scope '/:id', constraints: { id: /[^\/]+/ } do
    get 'course(.:format)', to: 'courses#show', as: :course
    patch 'course(.:format)', to: 'courses#update'
    delete 'course(.:format)', to: 'courses#destroy'
    get 'course/edit(.:format)', to: 'courses#edit', as: :edit_course
  end

  scope '/:course_id', constraints: { course_id: /[^\/]+/ } do
    # TODO(pwnall): remove the format specifier when the following bug gets
    #               fixed - https://github.com/rails/rails/issues/22747
    root 'session#show', as: :course_root, format: 'html'

    resources :prerequisites, except: [:show]
    resources :time_slots, only: [:index, :create, :destroy]

    # Student registration.
    resources :registrations,
              only: [:index, :show, :new, :create, :edit, :update] do
      member do
        patch :restricted
      end
    end

    # Staff registration.
    resources :role_requests, only: [:index, :new, :create, :show, :destroy] do
      member do
        post :approve
        post :deny
      end
    end

    # Recitations.
    resources :recitation_sections, except: [:show] do
      collection do
        post :autoassign
      end
    end
    resources :recitation_partitions, only: [:index, :show, :destroy]  do
      member do
        post :implement
      end
    end

    # Homework.
    resources :assignments do
      member do
        get :dashboard
        patch :schedule
        patch :deschedule
        patch :release
        patch :unrelease
        patch :release_grades
      end
      resources :extensions, controller: :deadline_extensions,
          only: [:index, :create]
    end
    resources :deadline_extensions, only: [:destroy]
    resources :assignment_files, only: [] do
      member do
        get :download
      end
    end
    resources :grades, only: [:index, :create] do
      collection do
        get :editor
        get :request_report, :request_missing
        post :for_user, :missing, :report
      end
    end
    resources :grade_comments, only: [:create]
    resources :exams, only: [] do
      resources :attendances, controller: :exam_attendances, only: [:index]
    end
    resources :exam_sessions, only: [] do
      resources :attendances, controller: :exam_attendances, only: [:create]
    end
    resources :attendances, controller: :exam_attendances, only: [:update,
        :destroy]

    # Homework submission.
    resources :analyzers, only: [] do
      collection do
        get :help
      end
      member do
        get :source
      end
    end
    resources :deliverables do
      member do
        get :submission_dashboard
        post :reanalyze
      end
    end
    resources :assignment_metrics
    resources :submissions, only: [:index, :create, :destroy] do
      member do
        get :file
        post :reanalyze
        post :promote
      end
      collection do
        get :request_package
        post :xhr_deliverables
        post :package_assignment
      end
      resources :collaborations, only: [:create, :destroy], shallow: true
    end
    resources :analyses, only: [:show] do
      member do
        get :refresh
      end
    end

    # Surveys.
    scope shallow_prefix: :survey do
      resources :surveys do
        resources :responses, controller: :survey_responses,
            only: [:index, :create, :update], shallow: true
      end
    end

    # Teams.
    resources :team_memberships, only: [:create, :destroy]
    resources :team_partitions do
      member do
        patch :lock
        patch :unlock
        get :issues
      end
    end

    resources :teams, only: [:edit, :create, :update, :destroy]
    # Teams / Student view.
    get '/teams_student', to: 'teams_student#show'
    post '/teams_student/leave_team', to: 'teams_student#leave_team', as: :leave_team
    post '/teams_student/create_team', to: 'teams_student#create_team'
    post '/teams_student/invite_member', to: 'teams_student#invite_member'
    post '/teams_student/accept_invitation', to: 'teams_student#accept_invitation'
    post '/teams_student/ignore_invitation', to: 'teams_student#ignore_invitation'
    resources :teams_student
  end

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/assignment_file.rb
# == Schema Information
#
# Table name: assignment_files
#
#  id                 :integer          not null, primary key
#  description        :string(64)       not null
#  assignment_id      :integer          not null
#  file_blob_id       :string(48)       not null
#  file_size          :integer          not null
#  file_mime_type     :string(64)       not null
#  file_original_name :string(256)      not null
#  released_at        :datetime
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

# Wraps a file relevant to an assignment.
#
# Examples include the assignment description, solutions, and test cases.
class AssignmentFile < ApplicationRecord
  include IsReleased

  # A brief description of the resource. E.g., "PS1 Solutions".
  validates :description, length: 1..64, presence: true

  # The wrapped file.
  has_file_blob :file, allows_nil: false, blob_model: 'FileBlob'

  # Refuse to serve active content from the site.
  validates :file_mime_type, exclusion: {
      in: ['text/html', 'application/xhtml+xml'] }

  # The relevant assignment.
  belongs_to :assignment, inverse_of: :files
  validates :assignment, presence: true

  # The course for which this file has been uploaded.
  has_one :course, through: :assignment

  # True if the file's release date has passed.
  def released?
    !!released_at && (released_at < Time.current)
  end

  # True if the given user is allowed to see this file.
  #
  # TODO(spark008): Add checks to this and other model permission methods to
  #     ensure that the user is a student registered for the course.
  def can_read?(user)
    (released? && assignment.released_for_student?(user)) ||
        assignment.can_edit?(user)
  end

  # The default release date for a particular resource file.
  #
  # This same method should also be defined for Assignment.
  def default_released_at
    assignment.released_at || self.class.default_released_at
  end
end

app/controllers/assignment_files_controller.rb
class AssignmentFilesController < ApplicationController
  before_action :set_current_course
  before_action :authenticated_as_user

  # GET /6.006/assignment_files/1/download
  def download
    @file = AssignmentFile.find params[:id]
    return bounce_user unless @file.can_read? current_user

    # NOTE: The CSP header provides some protection against an attacker who
    #       tries to serve active content (HTML+JS) using the server's origin.
    #       DbFile also explicitly disallows the HTML and XHTML MIME types.
    response.headers['Content-Security-Policy'] = "default-src 'none'"
    send_file_blob @file.file
  end
end

app/views/assignment_files/_fields.html.erb
<section class="file callout" data-pwnfx-hide-positive="file-section"
         data-pwnfx-scope="file">
  <%= f.row do %>
    <%= f.text_field :description, required: true,
          placeholder: 'Lab 1: Code Samples', label: 'Description' %>
    <div class="small-3 columns">
      <%= f.destroy_record_field :_destroy, data: { pwnfx_hide: 'file-section',
            pwnfx_hide_scope: 'file', pwnfx_hide_class: 'destroyed-blur',
            pwnfx_hide_trigger: 'checked' } %>
    </div>
  <% end %>

  <%= f.row do %>
  <%# The form does not save an uploaded file if there are any validation errors
      throughout the form. So the least confusing way to handle invalid files is
      to bounce attempts to submit the form until a valid file is uploaded.

      TODO(spark008): Add some JS to bounce files with invalid MIME types. %>
    <%= f.file_field :file, label: 'Resource file',
                            required: !f.object.file.blob_id %>
    <div class="small-3 columns">
      <span class="comment">
        <% if f.object.file.blob_id %>
          <%= link_to download_assignment_file_path(f.object,
                course_id: f.object.course) do %>
            <%= download_icon_tag %> <%= f.object.file_original_name %>
          <% end %>
          (<%= number_to_human_size f.object.file_size %>)
        <% end %>
      </span>
    </div>
  <% end %>

  <%= f.row do %>
    <%= f.datetime_local_field :released_at,
          value: released_at_with_default(f.object), step: 1, required: true,
          data: f.optional_input_data('file'), label: 'Release date' %>
    <div class="columns">
      <%= f.check_box :reset_released_at,
            data: f.disable_switch_data('file'), label: 'Undecided' %>
    </div>
  <% end %>
</section>

app/views/assignment_files/_list.html.erb
<table class="files">
  <thead>
    <tr>
      <th class="file-name">File</th>
      <th class="description">Description</th>
      <th class="size">Size</th>
      <th class="uploaded">Uploaded</th>
    </tr>
  </thead>
  <tbody>
    <% assignment.files_for(current_user).each do |file| %>
    <tr>
      <td class="file-name">
        <%= link_to download_assignment_file_path(file,
              course_id: file.course) do %>
          <%= download_icon_tag %> <%= file.file_original_name %>
        <% end %>
      </td>
      <td class="description"><%= file.description %></td>
      <td class="size"><%= number_to_human_size file.file_size %></td>
      <td class="uploaded"><%= file.updated_at.to_s(:deadline_long) %></td>
    </tr>
    <% end %>
  </tbody>
</table>