config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'session#show'

  # Site-wide functionality.
  scope '/_' do
    authpwn_session
    resources :courses, only: [:index, :new, :create] do
      collection do
        get :connect
      end
    end

    # Account registration.
    resources :users do
      collection do
        post :check_email
      end
      member do
        post :impersonate
        patch :set_admin
        patch :confirm_email
      end
    end
    resources :profile_photos do
      member do
        get :profile, :thumb
      end
    end

    # Staff registration.
    resources :roles, only: [:destroy]

    # Background jobs.
    resources :jobs, only: [:index, :show] do
      collection do
        delete :failed, action: :destroy_failed
      end
    end

    # API.
    scope '/api', defaults: { format: 'json' } do
      get '0/user_info' => 'api#user_info', as: :api_user_info_v0
      get '0/assignments' => 'api#assignments', as: :api_assignments_v0
      get '0/submissions' => 'api#submissions', as: :api_submissions_v0
    end

    # API documentation.
    get 'api_docs' => 'api_docs#index', as: :api_docs

    # E-mail resolver configuration.
    resources :email_resolvers

    # E-mail SMTP server configuration.
    resource :smtp_server, only: [:edit, :update]

    resources :feedback, only: [:new]

    # Exception handling test.
    get '/crash' => 'crash#crash'
  end

  # Course-specific URLs. Most functionality falls here.
  scope '/:id', constraints: { id: /[^\/]+/ } do
    get 'course(.:format)', to: 'courses#show', as: :course
    patch 'course(.:format)', to: 'courses#update'
    delete 'course(.:format)', to: 'courses#destroy'
    get 'course/edit(.:format)', to: 'courses#edit', as: :edit_course
  end

  scope '/:course_id', constraints: { course_id: /[^\/]+/ } do
    # TODO(pwnall): remove the format specifier when the following bug gets
    #               fixed - https://github.com/rails/rails/issues/22747
    root 'session#show', as: :course_root, format: 'html'

    resources :prerequisites, except: [:show]
    resources :time_slots, only: [:index, :create, :destroy]

    # Student registration.
    resources :registrations,
              only: [:index, :show, :new, :create, :edit, :update] do
      member do
        patch :restricted
      end
    end

    # Staff registration.
    resources :role_requests, only: [:index, :new, :create, :show, :destroy] do
      member do
        post :approve
        post :deny
      end
    end

    # Recitations.
    resources :recitation_sections, except: [:show] do
      collection do
        post :autoassign
      end
    end
    resources :recitation_partitions, only: [:index, :show, :destroy]  do
      member do
        post :implement
      end
    end

    # Homework.
    resources :assignments do
      member do
        get :dashboard
        patch :schedule
        patch :deschedule
        patch :release
        patch :unrelease
        patch :release_grades
      end
      resources :extensions, controller: :deadline_extensions,
          only: [:index, :create]
    end
    resources :deadline_extensions, only: [:destroy]
    resources :assignment_files, only: [] do
      member do
        get :download
      end
    end
    resources :grades, only: [:index, :create] do
      collection do
        get :editor
        get :request_report, :request_missing
        post :for_user, :missing, :report
      end
    end
    resources :grade_comments, only: [:create]
    resources :exams, only: [] do
      resources :attendances, controller: :exam_attendances, only: [:index]
    end
    resources :exam_sessions, only: [] do
      resources :attendances, controller: :exam_attendances, only: [:create]
    end
    resources :attendances, controller: :exam_attendances, only: [:update,
        :destroy]

    # Homework submission.
    resources :analyzers, only: [] do
      collection do
        get :help
      end
      member do
        get :source
      end
    end
    resources :deliverables do
      member do
        get :submission_dashboard
        post :reanalyze
      end
    end
    resources :assignment_metrics
    resources :submissions, only: [:index, :create, :destroy] do
      member do
        get :file
        post :reanalyze
        post :promote
      end
      collection do
        get :request_package
        post :xhr_deliverables
        post :package_assignment
      end
      resources :collaborations, only: [:create, :destroy], shallow: true
    end
    resources :analyses, only: [:show] do
      member do
        get :refresh
      end
    end

    # Surveys.
    scope shallow_prefix: :survey do
      resources :surveys do
        resources :responses, controller: :survey_responses,
            only: [:index, :create, :update], shallow: true
      end
    end

    # Teams.
    resources :team_memberships, only: [:create, :destroy]
    resources :team_partitions do
      member do
        patch :lock
        patch :unlock
        get :issues
      end
    end

    resources :teams, only: [:edit, :create, :update, :destroy]
    # Teams / Student view.
    get '/teams_student', to: 'teams_student#show'
    post '/teams_student/leave_team', to: 'teams_student#leave_team', as: :leave_team
    post '/teams_student/create_team', to: 'teams_student#create_team'
    post '/teams_student/invite_member', to: 'teams_student#invite_member'
    post '/teams_student/accept_invitation', to: 'teams_student#accept_invitation'
    post '/teams_student/ignore_invitation', to: 'teams_student#ignore_invitation'
    resources :teams_student
  end

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/survey.rb
# == Schema Information
#
# Table name: surveys
#
#  id         :integer          not null, primary key
#  name       :string(128)      not null
#  released   :boolean          not null
#  course_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

# The set of questions used in a survey.
class Survey < ApplicationRecord
  include HasDeadline

  # A name for the question set. Visible to admins.
  validates :name, length: { in: 1..128, allow_nil: false },
      uniqueness: { scope: :course }

  # Whether the survey has been released and users can submit responses.
  validates :released, inclusion: { in: [true, false], allow_nil: false }

  # The course in which this survey is administered.
  belongs_to :course, inverse_of: :surveys
  validates :course, presence: true

  # The questions that constitute this survey.
  has_many :questions, class_name: 'SurveyQuestion', inverse_of: :survey,
                       dependent: :destroy
  accepts_nested_attributes_for :questions, allow_destroy: true,
                                            reject_if: :all_blank

  # The responses to this survey.
  has_many :responses, class_name: 'SurveyResponse', inverse_of: :survey,
      dependent: :destroy

  # True if the given user has responded to this survey.
  def answered_by?(user)
    !!responses.where(user: user).first
  end

  # True if the given user is allowed to see or respond to this survey.
  #
  # An equivalent method with the same name must be defined for Assignment so
  # the method can be called on either class.
  def can_submit?(user)
    (released? && course.is_student?(user)) || course.can_edit?(user)
  end

  # True if the given user is allowed to change or delete this survey.
  def can_edit?(user)
    course.can_edit? user
  end

  def can_delete?(user)
    return true if user && user.admin?
    (!released? || responses.empty?) && can_edit?(user)
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  include SidebarLayout

  before_action :set_current_course
  before_action :authenticated_as_user, only: [:index, :show]
  before_action :authenticated_as_course_editor, except: [:index, :show]
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  def index
    @surveys = current_course.surveys_for current_user

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /surveys/1
  def show
    return bounce_user unless @survey.can_submit? current_user

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /surveys/new
  def new
    @survey = Survey.new course: current_course
    @survey.due_at = @survey.default_due_at

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  def create
    @survey = Survey.new survey_params
    @survey.course = current_course
    @survey.released = false

    respond_to do |format|
      if @survey.save
        format.html do
          redirect_to edit_survey_url(@survey, course_id: @survey.course)
        end
      else
        format.html { render :new }
      end
    end
  end

  # PUT /surveys/1
  def update
    respond_to do |format|
      if @survey.update survey_params
        format.html do
          redirect_to surveys_url(course_id: @survey.course),
              notice: 'Survey was successfully updated.'
        end
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /surveys/1
  def destroy
    respond_to do |format|
      if @survey.can_delete? current_user
        @survey.destroy
        format.html do
          redirect_to surveys_url(course_id: @survey.course),
              notice: 'Survey was deleted.'
        end
      else
        format.html do
          redirect_to surveys_url(course_id: @survey.course),
              notice: 'Survey could not be deleted.'
        end
      end
    end
  end

  def set_survey
    @survey = current_course.surveys.find params[:id]
  end
  private :set_survey

  # NOTE: We allow the :id parameter in the has_many association's attributes
  #     hash since accepts_nested_attributes_for checks that each nested record
  #     actually belongs to the parent record.
  def survey_params
    params.require(:survey).permit :name, :released, :due_at,
        questions_attributes: [:id, :prompt, :_destroy, :type, :step_size,
        :allows_comments, :scaled, :scale_min, :scale_max, :scale_min_label,
        :scale_max_label ]
  end
  private :survey_params
end

app/helpers/surveys_helper.rb
module SurveysHelper
  # The text to show on the button that (un)releasees a survey.
  def survey_release_text(survey)
    survey.released? ? 'Pull release' : 'Release'
  end
end

app/views/surveys/_fields.html.erb
<%= f.text_field :name, placeholder: 'Lab 1 Survey', required: true,
                            autofocus: true, label: 'Name' %>
<%= f.datetime_local_field :due_at, step: 1, label: 'Response Deadline' %>

app/views/surveys/_form.html.erb
<div class="survey-builder" data-pwnfx-scope="survey">
  <%= foundation_form_for survey, url: polymorphic_path(survey,
        course_id: survey.course) do |f| %>

    <%= render 'surveys/fields', f: f %>

    <h3>Questions</h3>
    <div class="survey-builder-questions"
         data-pwnfx-render-target="qo-question qs-question">
      <%= f.fields_for :questions do |qf| %>
        <%= render 'survey_questions/fields', f: qf %>
      <% end %>
    </div>
    <div class="survey-builder-actions row align-center">
      <div class="small-6 columns">
        <%= select_tag :type, question_types_for_select,
              data: { pwnfx_showif_source: 'question-type' },
              class: 'question-type' %>
      </div>
      <div class="small-4 columns">
        <span class="forked-button-wrapper">
          <%= button_tag data: { pwnfx_render_scope: 'survey',
                pwnfx_render_randomize: 'IDID', pwnfx_render: 'qo-question',
                pwnfx_showif: 'question-type', pwnfx_showif_scope: 'survey',
                pwnfx_showif_is: 'QuantitativeScaledQuestion',
                pwnfx_showif_replace: 'button' }, class: 'hollow button' do %>
            <%= create_icon_tag %> Add a question
          <% end %>
          <%= button_tag data: { pwnfx_render_scope: 'survey',
                pwnfx_render_randomize: 'IDID', pwnfx_render: 'qs-question',
                pwnfx_showif: 'question-type', pwnfx_showif_scope: 'survey',
                pwnfx_showif_is: 'QuantitativeOpenQuestion',
                pwnfx_showif_replace: 'button' }, class: 'hollow button' do %>
            <%= create_icon_tag %> Add a question
          <% end %>
        </span>
      </div>
    </div>
    <script type="text/html" data-pwnfx-render-source="qo-question">
      <%= f.fields_for :questions, QuantitativeScaledQuestion.new,
                                   child_index: 'IDID' do |qf| %>
        <%= render 'survey_questions/fields', f: qf %>
      <% end %>
    </script>
    <script type="text/html" data-pwnfx-render-source="qs-question">
      <%= f.fields_for :questions, QuantitativeOpenQuestion.new,
                                   child_index: 'IDID' do |qf| %>
        <%= render 'survey_questions/fields', f: qf %>
      <% end %>
    </script>

    <%= submit_button_tag do %>
      <%= save_icon_tag %> Update Survey
    <% end %>
  <% end %>
</div>

app/views/surveys/_list.html.erb
<% surveys.each do |survey| %>
  <%= render 'surveys/show', survey: survey %>
<% end %>

app/views/surveys/_show.html.erb
<section class="survey">
  <h3 class="title-with-actions">
    <span class="title"><%= survey.name %></span>

    <% if survey.can_edit? current_user %>
    <span class="actions">
      <span class="link-button-wrapper">
        <%= link_to survey_responses_path(survey_id: survey,
              course_id: survey.course), class: 'hollow button' do %>
          <%= dashboard_icon_tag %> Responses
        <% end %>
      </span>
      <span class="link-button-wrapper">
        <%= link_to edit_survey_path(survey, course_id: survey.course),
              class: 'hollow button' do %>
          <%= edit_icon_tag %> Edit
        <% end %>
      </span>
      <% if survey.can_delete?(current_user) %>
        <%= button_to survey_path(survey, course_id: survey.course), data: {
              confirm: 'Are you sure?' }, class: 'hollow alert button',
              method: :delete do %>
          <%= destroy_icon_tag %> Delete
        <% end %>
      <% end %>
      <%= button_to survey_path(survey, course_id: survey.course,
            survey: { released: !survey.released? }), class: 'hollow button',
            method: :patch do %>
        <%= release_icon_tag %> <%= survey_release_text survey %>
      <% end %>
    </span>
    <% end %>
  </h3>

  <p class="lead deadline">
    Due
    <%= survey.due_at.to_s(:deadline_long) %>
    <%= time_delta_in_words survey.due_at %>
  </p>

  <section class="response">
    <% if survey.can_submit? current_user %>
      <%= render 'survey_responses/form',
            response: response_for(@response, current_user, survey) %>
    <% end %>
  </section>
</section>

app/views/surveys/edit.html.erb
<h2>Survey Builder</h2>

<%= render 'surveys/form', survey: @survey %>

app/views/surveys/index.html.erb
<h2 class="title-with-actions">
  <span class="title">Surveys</span>
  <% if current_course.can_edit? current_user %>
  <span class="actions">
    <span class="link-button-wrapper">
      <%= link_to new_survey_path(course_id: current_course),
            class: 'hollow button' do %>
        <%= create_icon_tag %> New
      <% end %>
    </span>
  </span>
  <% end %>
</h2>
<%= render 'surveys/list', surveys: @surveys %>

app/views/surveys/new.html.erb
<h2>New Survey</h2>

<%= foundation_form_for @survey, url: polymorphic_path(@survey,
      course_id: @survey.course) do |f| %>
  <%= render 'surveys/fields', f: f %>

  <%= submit_button_tag do %>
    <%= build_icon_tag %> Build Survey
  <% end %>
<% end %>

app/views/surveys/show.html.erb
<%= render 'surveys/show', survey: @survey %>